package spec

// DefaultTemplate is the harness.yaml generated by `harness init`.
const DefaultTemplate = `version: harnesslab/v1

name: golang-coding-default

runtime:
  type: trpc

agent:
  type: coding

model:
  provider: openai
  model: gpt-5
  temperature: 0.1

planning:
  strategy: todo

tools:
  filesystem: false
  shell: true
  git: false
  search: false

verification:
  strategy: final
  commands:
    - go test ./...
    - go vet ./...

success:
  require_verification_pass: true
  require_workspace_change: false

retry:
  max_model_errors: 3
  max_tool_errors: 3

sandbox:
  type: none
  network: restricted

budget:
  max_tokens: 120000
  max_cost_usd: 5
  timeout: 20m
`
